-- :help options
vim.opt.autoindent = true			-- new lines inherit the indentation of previous lines
vim.opt.backup = false				-- creates a backup file
vim.opt.clipboard = "unnamedplus"			-- allow neovim to access the system clipboard
vim.opt.cmdheight = 2				-- more space in the nvim command line for displaying messages
vim.opt.conceallevel = 0			-- so that `` is visible in markdown files
vim.opt.fileencoding = "utf-8"			-- the encoding written to a file
vim.opt.hlsearch = true				-- highlight all matches on previous search
vim.opt.history = 1000				-- increase the undo limit
vim.opt.ignorecase = true			-- ignore case when searching
vim.opt.incsearch = true			-- shows partial matches when searching
vim.opt.mouse = "a"				-- allow mouse to be used in all files in nvim
--vim.opt.showtabline = 2				-- always show tab line
vim.opt.smartcase = true			-- smart case
vim.opt.smartindent = true			-- make indenting smarter again
vim.opt.splitbelow = true			-- force all horizontal splits to go below current window
vim.opt.splitright = true			-- force all vertical splits to go to the right of the current window
vim.opt.swapfile = false			-- creates a swapfile
vim.opt.timeoutlen = 1000			-- time in ms for a mapped sequence to complete
vim.opt.undofile = true				-- enable persistent undo
vim.opt.updatetime = 300			-- faster completion (4000ms by default)
--vim.opt.cursorline = true			-- highlight current line
vim.opt.number = true				-- set numbered lines
vim.opt.relativenumber = true			-- set relative numbered lines
vim.opt.numberwidth = 4				-- set number column width to 2 (default 4)
--vim.opt.signcolumn = "yes"			-- always show the sign column, otherwise it would shift the text each time
vim.opt.wrap = false				-- display lines as one long line instead of wrapping
vim.opt.scrolloff = 8				-- set the minimal lines above or below the cursor so that it is visible what is being done
vim.opt.sidescrolloff = 8			-- same as previous but for horizontal axis
vim.opt.guifont = "monospace:h17"		-- the font used in graphical nvim applications
